title: bittorbarriola9
subtitle: 
description: ""
url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog
    - text: Gallery
      url: /gallery
    - text: Shop
      url : /shop
    - text: Contact
      url : /contact

# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile_bb9.png
author: Bittor Barriola
author_bio: "Hi, my name is Bittor Barriola Artieda, bittorbarriola9 on most of my social networks.<br />I'm a mechanical engineer, working as an IT technician.<br />Since I was little I have been passionate about technology, all kinds of technology, and luckily, now I can work with it in my daily!\U0001F60E<br />On my free time I like to practice sport, different type of sports. You can find me doing may workout at the gym about 5 times per week. If not, I will be playing football, padel or riding a bike.<br />Bellow you can find more information about my experience. If you like this page, you can buy me a coffee to have fuel to continue typing here, or at least you can give me a &#128153; on my social profiles."
author_email: "bittorbarriola9@gmail.com"
author_location: Zizur Nagusia (Spain)
author_website_url: "https://bittorbarriola9.github.io"
typewrite-text: Trying to code somthing...
hero_cover_img: sample_cover.jpg

# Work Experience
author_work_experience:
  - company_name: BSH
    company_logo: logo_BSH.png
    company_url: https://www.bsh-group.com/
    designation: IT-Technician, Software Engineer
    period: [Jan 2022 - ... ]
    description: RFID Technology implementation / Indrustrial Device Management / Industrial Labelling
    visibility: true
  - company_name: Tigloo
    company_logo: logo_tigloo.jpg
    company_url: https://www.tigloo.es/
    designation: IT-Technician, Software Engineer for BSH
    period: [Apr 2021 - Dec 2021]
    description: RFID Technology implementation / Indrustrial Device Management / Industrial Labelling
    visibility: true
  - company_name: BSH
    company_logo: logo_BSH.png
    company_url: https://www.bsh-group.com/
    designation: Scholarship
    period: [Feb 2020 - Mar 2021]
    description: RFID Technology implementation / Indrustrial Device Management / Industrial Labelling
    visibility: true    
  - company_name: CBL Logística
    company_logo: logo_CBL.png
    company_url: https://www.cbl-logistica.com/
    designation: Warehouse Employee
    period: [Mar 2018 - Jan 2020]
    description: Trucks unloading / Warehouse organization / Shipments preparation
    visibility: true

# Education
author_education:
  - college_logo: logo_upna.png
    college_name: Universidad Púbblica de Navarra
    college_url: https://www.unavarra.es/portada
    college_degree: Mechanical Engineering
    description: ETSIIIT
    visibility: true
  - college_logo: logo_ies_zizur.jpg
    college_name: IES Zizur BHI
    college_url: https://ieszizurbhi.educacion.navarra.es/web/
    college_degree: High School Degree and Bachelor
    description: Technology Area
    visibility: true
  - college_logo: logo_erreniega.jpg
    college_name: Erreniega IP
    college_url: https://erreniegaip.educacion.navarra.es/web/es/
    college_degree: Primary School
    description: First knownledges
    visibility: true

# Projects
author_projects:
  - project_thumbnail: project_jekyll.png
    project_title: bittorbarriola9
    project_description: My webpage hosted in GitHub Pages, built using Jekyll 
    project_url: https://bittorbarriola9.github.io
    repository_url: https://github.com/bittorbarriola9/bittorbarriola9.github.io
    visibility: true

#Others Experiences
author_other_experiences:
  - company_name: Ardoi Pilota Elkartea
    company_logo: logo_ardoi.jpeg
    company_url: https://www.facebook.com/profile.php?id=100075420652664
    designation: Kids Sport Campus Monitor
    period: [2011 - 2018]
    description: RFID Technology implementation / Indrustrial Device Management / Industrial Labelling
    visibility: true
  - company_name: CF Ardoi
    company_logo: logo_ardoi.jpeg
    company_url: https://twitter.com/ardoifutbol?s=20
    designation: Kids Sport Campus Monitor
    period: [2019]
    description: RFID Technology implementation / Indrustrial Device Management / Industrial Labelling
    visibility: true

#Sport Experience
author_sports_path:
  - title: CF Ardoi - 1st Team
    sport: Football
    team_name: CF Ardoi
    logo: logo_3rfef.png
    period: 2022 - 2023
    achivements: 
    url: https://twitter.com/ardoifutbol?s=20
    visibility: true
  - title: CF Ardoi - 1st Team
    sport: Football
    team_name: CF Ardoi
    logo: logo_2rfef.jpg
    period: 2021 - 2022
    achivements: 
    url: https://twitter.com/ardoifutbol?s=20
    visibility: true
  - title: CF Ardoi - 1st Team
    sport: Football
    team_name: CF Ardoi
    logo: logo_3a.jpeg
    period: 2016 - 2021
    achivements: 
    url: https://twitter.com/ardoifutbol?s=20
    visibility: true
  - title: CF Ardoi - Base
    sport: Football
    team_name: CF Ardoi
    logo: logo_ardoi.jpeg
    period: 2003 - 2016
    achivements: 
    url: https://twitter.com/ardoifutbol?s=20
    visibility: true
  - title: Ardoi Pilota Elkartea
    sport: Esku Pilota
    team_name: Ardoi Pilota Elkartea
    logo: logo_ardoi.jpeg
    period: 2002 - 2017
    achivements: 
    url: https://www.facebook.com/profile.php?id=100075420652664
    visibility: true



# social links
twitter_username: bittorbarriola9
github_username:  bittorbarriola9
facebook_username: bittorbarriola9
linkedin_username: bittorbarriolaartieda
instagram_username: bittorbarriola9
telegram_username: bittorbarriola9
#behance_username: johndoe
#medium_username: johndoe
#dribbble_username: johndoe
#flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
#hyvor_talk_website_id: 476

# wakatime username (coding activity)
#wakatime_username: sujaykundu777

# mailchimp embedded form url (newsletter):
#mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# contact form - (choose formspress or getform)
# getform_endpoint: 83b703c3-9e47-4df4-ac55-e24d7eb02abc
formspree_email: bittorbarriola9@gmail.com

# releases - widget can be (sidebar, modal or embed)
olvy_organization: devlopr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experience: true
show_author_other_experiences: true
show_author_education: true
show_author_projects: true
show_author_sports_path: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-admin

# Jekyll Admin Config
jekyll_admin:
  # hidden_links:
  #   - posts
  #   - pages
  #   - staticfiles
  #   - datafiles
  #   - configuration
  homepage: "posts"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
# gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md

destination: ./build